### ISSUE TITLE
RSS feed migration

### ISSUE THREAD

**Issue by bertrandbo** [cassiomolin/cassiomolin.github.io#1]
Recently, I've got synchronization issue with your blog in my RSS client.

Following your migration to Jekyll, the [former RSS feed](http://cassiomolin.com/feed/) is broken.

Would be nice if you could put it back.

Thanks !

**Comment by cassiomolin** [comment]
Looks like the migration has broken the feed. As a workaround, please use http://cassiomolin.com/feed.xml.

**Comment by bertrandbo** [comment]
The new feed is enough for me. I didn't see any RSS icon or html link in the page source code so I though you just dropped it !

Thank you !

**Comment by cassiomolin** [comment]
I really appreciate your interest in the blog. There are a few improvements to be done. Hopefully I'll be able to address them anytime soon.
